# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXBJKObbwtO7fZCZWfaoXOOkYaYvJ0D4
"""

#Foydalanuvchidan son kiritish
number = float(input(" kvadrat va kubini hisoblash uchun bir son kiriting: "))

#Kvadrat va kubni hisoblash
square = number ** 2
cube = number ** 3

#Natijalarni chiqarish
print(f"\nKiritilgan son: {number}")
print(f"Kvadrati: {square}")
print(f"Kubi: {cube}")